### ISSUE TITLE
Opt into thread jobs

### ISSUE THREAD

**Issue by scallyw4g** [scallyw4g/bonsai#13]
Right now games have to provide an implementation for every thread queue job, most of which are identical across games, _and_ have nothing to do with the game.

We should have a system that provides default implementations of the jobs, and something that lets us override the default .. probably a compile-time #define for each job which users set to 1 if they want to override .. or something like this.

Could probably metaprogram the defines such that we don't have the annoying manual step of going to add that every time we add a new thread job.

**Comment by PaulSteele34** [comment]
Conditional constexpr is another way that this could be done, I think. Like this?

#include <iostream>

// Default implementation of a job
constexpr void defaultJob() {
    std::cout << "Executing default job." << std::endl;
}

// Overridden implementation of the job
constexpr void overriddenJob() {
    std::cout << "Executing overridden job." << std::endl;
}

template<bool UseDefault = true>
void processJob() {
    if constexpr (UseDefault) {
        defaultJob();
    } else {
        overriddenJob();
    }
}

int main() {
    processJob();  // Uses the default implementation
    processJob<false>();  // Uses the overridden implementation

    return 0;
}

**Comment by scallyw4g** [comment]
@PaulSteele34 Sorry, I didn't notice this comment!

I decided to implement a runtime solution because I'd prefer to distribute a static engine binary.

The engine passes all events through the game thread callback, and the game can choose to handle them, or not.  The game returns True if it handled the event, and False otherwise.  The engine handles the ones the game cedes.

https://github.com/scallyw4g/bonsai/blob/0297883e40deb2cb34fb8d836f94a4392c45d3ce/src/engine/work_queue.h#L129
