### ISSUE TITLE
Black boxes on nvidia/linux

### ISSUE THREAD

**Issue by scallyw4g** [scallyw4g/bonsai#51]
Shawnecy reported some sparkling black boxes on linux.  We investigated for an hour or two but didn't get to the bottom of them.  What we found out:

* They appear during the gaussian blur of the bloom texture
* They reduce in frequency quickly on startup, sometimes surging in frequency again for short amounts of time
* It appears they are not caused by an error in the lighting shader calculations
* The only system we've seen them repro on is his; a 4090 on driver (IIRC 515.something) ( the screenshot he sent disappeared in discord)

**Comment by Shawnecy** [comment]
The artifacts in question:

![image](https://github.com/scallyw4g/bonsai/assets/6253755/2d2536e7-9401-497e-92bc-2940f66eb886)

These artifacts are positioned consistently across multiple executions of the application. I took a screenshot of the program immediately after startup multiple times, and the images are all the same as above.

If I resize the application window, the artifacts change aspect ratio to match:

![image](https://github.com/scallyw4g/bonsai/assets/6253755/98156401-62e4-4a14-b8f5-f3a32fabac21)

If I run the `turn_based` example project and load a fireball or if I load the `transparency` project, then the artifacts blink briefly before going away. The artifacts do not return if I load other projects, but they do return if I shut down `game_loader` and start it back up.

Removing this line from `api.cpp` eliminates the artifacts: 
```
if (Graphics->Settings.UseLightingBloom) { GaussianBlurTexture(&Graphics->Gaussian, &Graphics->Lighting.BloomTex, &Graphics->Lighting.BloomTextureFBO); }
```

I tinkered with this line in `Lighting.fragmentshader`, removing one term at a time and testing, and each time the artifacts remained:
```
    TotalLight = (Diffuse*KeyLightContrib*ShadowVisibility) +
                 (Diffuse*AmbientLightContrib*BlurredAO) +
                 (Diffuse*BackLightContrib*BlurredAO) +
                 (PointLightsContrib*BlurredAO) +
                 Fog;
```

---

My machine:
OS: Linux Mint 21.2 Victoria (Cinnamon) (x86_64)
Kernel: 5.15.0-94-generic
Screen resolution: 2560x1440
CPU: Intel i9-10900K (20) @ 5.300GHz
GPU: RTX 4090, 24gb
GPU Drivers: nvidia-driver-545 (545.29.06-0ubuntu0.22.04.2)

Those are the latest drivers for my OS, but the previous version (535.161.07-0ubuntu0.22.04.1) are the recommended drivers.

**Comment by scallyw4g** [comment]
This turned out to be a rat-hole and a half.  We finally narrowed it down to a divide by zero in the shader, which didn't make much sense to me, but still somehow corrupted the whole warp.  Would love to figure out what was going on there one day.
